### ISSUE TITLE
Add R version information to install instructions

### ISSUE THREAD

**Issue by amandalbradford** [PIFSC-Protected-Species-Division/LTabundR#14]
A colleague had trouble downloading `LTabundR` in an older version of R (<4.3). Let's note in the install instructions (on GitHub and the vignette) more information about compatible versions, perhaps the version used to compile the package and/or a recommended version.

**Comment by ericmkeen** [comment]
Done. The following language has been added to the Github home page for the package as well as the home page for the vignette: 

`LTabundR` depends upon `R` versions 2.10 or later. It was developed and published with `R` 4.3.1 on a 64-bit Mac OS.  You may need to download "Rtools" if it is not already installed on your computer. [You can do so here.](https://cran.r-project.org/bin/windows/Rtools/)
